[package]
name = "rustreexo"
version = "0.1.0"
authors = ["Calvin Kim <calvin@kcalvinalvin.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
